service:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080

crds:
  enabled: false
  create: false

rateLimit:
  create: false

authService:
  create: false
