repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: datawire
    url: https://www.getambassador.io
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

helmDefaults:
  tillerless: true
  verify: false
  wait: true
  timeout: 600
  force: true
  createNamespace: true

environments:
#  default:
  staging:

releases:
#  {{ if eq .Environment.Name "default" }}
#  - name: cluster-autoscaler
#    chart: stable/cluster-autoscaler
#    namespace: kube-system
#    version: 7.3.4
#    values:
#      - "./helm/charts/cluster-autoscaler/values.yaml"
#  {{ end }}
  - name: ambassador
    chart: datawire/ambassador
    namespace: ambassador
    version: 6.5.15
    values:
      - "./helm/charts/ambassador/values.yaml"
    set:
      - name: "service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-cert"
        value: ""
      - name: "service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-backend-protocol"
        value: "http"
      - name: "service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-ports"
        value: "443"
  - name: consul
    chart: hashicorp/consul
    namespace: consul
    version: 0.28.0
    values:
      - "./helm/charts/consul/values.yaml"
  - name: ambassador-config
    chart: ./helm/charts/ambassador-config
    namespace: ambassador
    needs:
      - ambassador/ambassador
      - consul/consul
    values:
      - "./helm/charts/ambassador-config/values.yaml"
  - name: passport-service
    chart: ./helm/charts/passport-service
    namespace: services
    needs:
      - ambassador/ambassador
    values:
      - "./helm/charts/passport-service/values.yaml"
