---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: {{ .Release.Namespace }}
spec:
  config:
    xff_num_trusted_hops: 1
    use_remote_address: false
    resolver: {{ .Values.consul.resolverName | quote }}
    load_balancer:
      policy: "round_robin"
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: tls
  namespace: {{ .Release.Namespace }}
spec:
  config:
    server:
      enabled: True
      redirect_cleartext_from: 8080
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: ambassador-host
  namespace: {{ .Release.Namespace }}
spec:
  hostname: {{ .Values.ambassador.hostname }}
  acmeProvider:
    authority: None
  requestPolicy:
    insecure:
      action: Route
